env:
  node: true
  es2020: true

extends: 
  - 'airbnb-base'
  - 'plugin: jest/recommended'

parserOptions:

  sourceType: module
  ecmaVersion: latest 

rules:
  no-console: 0

import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
  - error
  - ignorePackages
  - js: always
  no-undersccore-dangle: [2,{ "allow": ["__filename", "__dirname"] }]